bank/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('baiting/', include('scambaiting.urls')),
]

customer/urls.py
from django.urls import path, include

from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name="profile"),
    path('accounts/<int:account_id>', views.account_activity, name='account_activity'),
    path('accounts/', views.accounts, name='accounts'),
    path('transfer', views.transfer, name='transfer'),
]

scambaiting/urls.py
from django.urls import path, include

from . import views

app_name = 'scambaiting'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/new', views.add_contact, name='addContact'),
    path('contact/<int:contactID>', views.add_note, name="addNote"),
]

scambaiting/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


def Pushiness_Choices():
    return (
        ('Unknown', 'Unknown'),
        ('Not', 'Not Pushy'),
        ('Kinda', 'Kinda Pushy'),
        ('Pushy', 'Pushy'),
        ('Assholes', 'Assholes'),
        ('Sell', 'Sell Their Gmas For a Buck'),
    )


class PhoneSource(models.Model):
    text = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.text
  
    
class ScamType(models.Model):
    text = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.text    


class Contact(models.Model):
    phone_number = PhoneNumberField(unique=True)
    source = models.ForeignKey(PhoneSource, on_delete=models.CASCADE)
    url = models.URLField(max_length=300)
    added_ts = models.DateTimeField(auto_now_add=True)
    updated_ts = models.DateTimeField(auto_now=True)
    scam_type = models.ForeignKey(ScamType, on_delete=models.CASCADE)
    scam_specific_notes = models.TextField()
    tollfree = models.BooleanField(default=True)
    pushy = models.CharField(choices=Pushiness_Choices(), max_length=20, default="Unknown")
    
    def __str__(self):
        return str(self.phone_number)
    
    def note_count(self):
        return self.contactnote_set.count()
        
    
class ContactNote(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    note = models.TextField()
    added_ts = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.note[:30]
    

scambaiting/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm, TextInput
from .models import *


class ContactForm(ModelForm):
    
    class Meta:
        model = ContactNote
        fields = ['note']
        widgets = {
            'note': TextInput()
        }
        
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            

class AddContactForm(forms.ModelForm):
    
    class Meta:
        model = Contact
        fields = ('phone_number', 'source', 'url', 'scam_type', 'scam_specific_notes', 'tollfree', 'pushy')

scambaiting/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.conf import settings

from .forms import ContactForm, AddContactForm
from .models import Contact

def index(request):
    contacts = Contact.objects.all()
    return render(request, "baiting_index.html", {'contacts': contacts})

@login_required
def add_note(request, contactID):
    contact = Contact.objects.get(pk=contactID)
    notes = contact.contactnote_set.select_related().order_by('-pk')
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.instance.contact = contact
            form.save()
            url = reverse('scambaiting:addNote', kwargs={'contactID': contactID})
            return HttpResponseRedirect(url)
    else:
        form = ContactForm()
    context = {'contact': contact, 'notes': notes, 'form': form}
    return render(request, "add_note.html", context)


@login_required
def add_contact(request):
    if request.method == 'POST':
        form = AddContactForm(request.POST)
        if form.is_valid():
            form.save()
            url = reverse('scambaiting:index')
            return HttpResponseRedirect(url)
    else:
        form = AddContactForm()
    return render(request, "add_contact.html", {'form': form})

scambaiting/templates/add_contact.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <title>Scambaiting - Add New Contact</title>
{% endblock %}

{% block brand %}
    <a class="navbar-brand" href="{% url 'scambaiting:index' %}">Scambaiting</a>
{% endblock %}

{% block nav %}
{% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'scambaiting:index' %}">Back</a>
            </li>
{% endif %}
{% endblock %}

{% block content %}
    <h4 class="text-center"> Add New Contact </h4>
    <div class="formNote row">        
        <form action="{% url 'scambaiting:addContact' %}" method="post">
            {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-8">
                        {{ form.phone_number|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.scam_type|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.url|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.source|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.tollfree|as_crispy_field }}
                    </div>
                </div>
                    {{ form.pushy|as_crispy_field }}
                <div>
                    <input class="btn btn-success" type="submit" value="Submit">
                </div>
        </form>
    </div>
    
    <style>
    body {
        font-size: 1.5rem;
        width: 100%;
        background: #002B3C !important;
    }
    nav#mainNav {
        background: #246B61 !important;
        border-bottom: 10px solid #FF8100;
    }
    .contactinfo .col-sm-3 {
        padding: 10px;
        background: white;
        text-align: center;
    }
    .contactScamNote {
        background: white;
        padding: 10px;
        margin-top: 5px;
        text-align: center;
        border-radius: 5px;
    }
    .notes {
        background: white;
        margin-top: 5px;
        border-radius: 5px;
        padding: 5px;
        width: 100%;
    }
    .note{
        border-bottom: solid 1px #ddd;
        padding-bottom: 5px;
        width: 100% !important;
    }
    .formNote.row {
        background: white;
        margin-top: 10px;
        width: 100%;
        padding: 15px;
        border-radius: 5px;
    }
    a.nav-link {
        color: white !important;
        font-weight: bolder;
    }

    a.nav-link:hover {
        color: #F60022 !important;
    }
    h4.text-center {
        color: cornsilk;
        margin-top: 6px;
    }
    </style>
{% endblock %}

scambaiting/templates/add_note.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <title>Scambaiting - Add Note</title>
{% endblock %}

{% block brand %}
    <a class="navbar-brand" href="{% url 'scambaiting:index' %}">Scambaiting</a>
{% endblock %}

{% block nav %}
{% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'scambaiting:index' %}">Back</a>
            </li>
{% endif %}
{% endblock %}

{% block content %}
    <h4 class="text-center">
    Displaying Contact:
        <a href="{{contact.url}}" target="_bank">
            <span class="glyphicon glyphicon-earphone"></span>
        </a>
        {{contact.phone_number}}
    </h4>
    <div class="contactinfo row">
        <div class="source col-sm-3">
        Source: {{contact.source}}
        </div>
        <div class="added col-sm-3">
        Added: {{contact.added_ts|date:"H:i m/d/Y"}}
        </div>
        <div class="added col-sm-3">
        Last Call: {{contact.updated_ts|date:"H:i m/d/Y"}}
        </div>
        <div class="added col-sm-3">
        Scam Type: {{contact.scam_type}}
        </div>
    </div>
    <div class="contactScamNote row">
        <div class="col-sm-3">
            Dated Added: <br>
            {{contact.added_ts|date:"H:i m/d/Y"}}
        </div>
        <div class="col-sm-9">
            {{contact.scam_specific_notes}}
        </div>
    </div>
    <h4 class="text-center"> Add New Note </h4>
    <div class="formNote row">        
        <form class="col-sm-12" action="{% url 'scambaiting:addNote' contactID=contact.pk %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="col-sm-2 col-sm-offset-5">
                <input class="btn btn-success" type="submit" value="Submit">
            </div>
        </form>
    </div>
    <h4 class="text-center"> Previous Notes </h4>
    <div class="notes row">
        {% if notes|length > 0 %}
            {% for note in notes %}
            <div class="note">
                <div class="col-sm-3">
                    Last Contact: <br>
                    {{note.added_ts|date:"H:i m/d/Y"}}
                </div>
                <div class="col-sm-9">
                    {{note.note}}
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="note text-center"> No notes on this contact </div>
        {% endif %}
    </div>
    <style>
    body {
        font-size: 1.5rem;
        width: 100%;
        background: #002B3C !important;
    }
    nav#mainNav {
        background: #246B61 !important;
        border-bottom: 10px solid #FF8100;
    }
    .contactinfo .col-sm-3 {
        padding: 10px;
        background: white;
        text-align: center;
    }
    .contactinfo {
        border-radius: 5px;
    }
    .contactScamNote {
        background: white;
        padding: 10px;
        margin-top: 5px;
        text-align: center;
        border-radius: 5px;
    }
    .notes {
        background: white;
        margin-top: 5px;
        border-radius: 5px;
        padding: 5px;
    }
    .note{
        border-bottom: solid 1px #ddd;
        padding-bottom: 5px;
        width: 100% !important;
    }
    .formNote.row {
        background: white;
        margin-top: 10px;
        padding: 15px;
        border-radius: 5px;
    }
    a.nav-link {
        color: white !important;
        font-weight: bolder;
    }

    a.nav-link:hover {
        color: #F60022 !important;
    }
    h4.text-center {
        color: cornsilk;
        margin-top: 6px;
    }
    </style>
{% endblock %}

scambaiting/templates/baiting_index.html
{% extends 'base.html' %}

{% block title %}
    <title>Scambaiting</title>
{% endblock %}

{% block brand %}
    <a class="navbar-brand" href="{% url 'scambaiting:index' %}">Scambaiting</a>
{% endblock %}

{% block nav %}
{% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'scambaiting:addContact' %}">Add Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'customer:accounts' %}">FakeBank</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'scambaiting:index' %}">Back</a>
            </li>
{% endif %}
{% endblock %}

{% block content %}
    <div class="contacts">
        {% for contact in contacts %}
        <div class="contact col-md-4">
            <div class="card">
                <div class="container1">
                    <h4>
                        <a href="{{contact.url}}" target="_bank">
                            <span class="glyphicon glyphicon-earphone"></span>
                        </a>
                        <b class="center">{{contact.phone_number}}</b>
                    </h4>
                    <ul class="list-group"> 
                        <li class="list-group-item">Source: <span class="right">{{contact.source}}</span></li> 
                        <li class="list-group-item">Number Of Notes: <span class="badge">{{contact.note_count}}</span></li> 
                        <li class="list-group-item">Toll Free:
                        {% if contact.tollfree %}
                            <span class="right alert-success glyphicon glyphicon-check"></span>
                        {% else %}
                            <span class="right glyphicon glyphicon-unchecked"></span>
                        {% endif %}
                        </li> 
                        <li class="list-group-item">Scam Type:
                            <span class="right">{{contact.scam_type}}</span>
                        </li> 
                        <li class="list-group-item">Pushiness:
                            <span class="badge">{{contact.pushy}}</span>
                        </li> 
                    </ul>
                </div>
                <a href="{% url 'scambaiting:addNote' contactID=contact.pk %}" class="btn btn-success">Add Note</a>
            </div>
        </div>
        {% endfor %}
    </div>
<style>
h4{
    padding: 1.25rem;
}
span.right {
    float: right;
}
b.center {
    margin-left: 20%;
}
body {
    font-size: 1.5rem;
    width: 100%;
    background: #002B3C !important;
}
nav#mainNav {
    background: #246B61 !important;
    border-bottom: 10px solid #FF8100;
}
.contactinfo .col-sm-3 {
    padding: 10px;
    background: white;
    text-align: center;
}
.contactScamNote {
    background: white;
    padding: 10px;
    margin-top: 5px;
    text-align: center;
    border-radius: 5px;
}
.notes {
    background: white;
    margin-top: 5px;
    border-radius: 5px;
    padding: 5px;
    width: 100%;
}
.note{
    border-bottom: solid 1px #ddd;
    padding-bottom: 5px;
    width: 100% !important;
}
.formNote.row {
    background: white;
    margin-top: 10px;
    width: 100%;
    padding: 15px;
    border-radius: 5px;
}
.formNote label {
    float: left;
}

.formNote input.formControl {
    float: left !important;
}

.formNote button {
    float: left !important;
    width:  100px;
    background: green;
}
a.nav-link {
    color: white !important;
    font-weight: bolder;
}

a.nav-link:hover {
    color: #F60022 !important;
}
h4.text-center {
    color: cornsilk;
    margin-top: 6px;
}
</style>
{% endblock %}