bank/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('baiting/', include('scambaiting.urls')),
]

customer/urls.py
from django.urls import path, include

from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name="profile"),
    path('accounts/<int:account_id>', views.account_activity, name='account_activity'),
    path('accounts/', views.accounts, name='accounts'),
    path('transfer', views.transfer, name='transfer'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
    <title>Banking System</title>
    {% endblock %}
    {% load crispy_forms_tags %}
    <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet">
    <link href="{% static 'css/daterangepicker.css' %}" rel="stylesheet">
    <style>
      body {
          font-size: 1.5rem;
      }
      a.navbar-brand {
          font-size: large;
          line-height: 2;
      }
    </style>
  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        {% block brand %}
        <a class="navbar-brand js-scroll-trigger" href="{% url 'customer:index' %}">{{bank_name}}</a>
        {% endblock %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
            {% block nav %}
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'customer:accounts' %}">Accounts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'customer:transfer' %}">Transfer</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'customer:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              {% comment %} <a class="nav-link js-scroll-trigger" href="{% url 'account_logout' %}">Logout</a> {% endcomment %}
            </li>

            {% else %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'account_signup' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
            </ul>
            {% endblock %}
        </div>
      </div>
    </nav>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 mx-auto">
          <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
            {% endfor %}
        </ul>
    {% block content %}





{% endblock %}
             </div>
        </div>
      </div>
    </section>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>
{% block script %}
  {% endblock %}
  </body>

</html>

templates/base_backup.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
    <title>Banking System</title>
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'customer:index' %}">Banking System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'customer:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'account_logout' %}">Logout</a>
            </li>
          </ul>
            {% else %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'account_signup' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'account_login' %}">Login</a>
            </li>
            {% endif %}
        </div>
      </div>
    </nav>
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}> {{ message }}</li>
            {% endfor %}
        </ul>
    {% block content %}
    <header class="bg-primary text-white">
      <div class="container text-center">
        <h1>Welcome to Scrolling Nav</h1>
        <p class="lead">A landing page template freshly redesigned for Bootstrap 4</p>
      </div>
    </header>

    <section id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>About this page</h2>
            <p class="lead">This is a great place to talk about your webpage. This template is purposefully unstyled so you can use it as a boilerplate or starting point for you own landing page designs! This template features:</p>
            <ul>
              <li>Clickable nav links that smooth scroll to page sections</li>
              <li>Responsive behavior when clicking nav links perfect for a one page website</li>
              <li>Bootstrap's scrollspy feature which highlights which section of the page you're on in the navbar</li>
              <li>Minimal custom CSS so you are free to explore your own unique design options</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section id="services" class="bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Services we offer</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut optio velit inventore, expedita quo laboriosam possimus ea consequatur vitae, doloribus consequuntur ex. Nemo assumenda laborum vel, labore ut velit dignissimos.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact us</h2>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>
{% endblock %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}'"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>

  </body>

</html>