bank/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('baiting/', include('scambaiting.urls')),
]

customer/urls.py
from django.urls import path, include

from . import views

app_name = 'customer'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name="profile"),
    path('accounts/<int:account_id>', views.account_activity, name='account_activity'),
    path('accounts/', views.accounts, name='accounts'),
    path('transfer', views.transfer, name='transfer'),
]

customer/models.py
import uuid

from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from localflavor.us.models import USZipCodeField, USStateField
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200,null=True)
    birthday = models.DateField()
    phone = PhoneNumberField(null=True, blank=True)  
    street = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = USStateField(null=True, blank=True)
    country = models.CharField(max_length=50, default="USA")
    zip_code = USZipCodeField(null=True, blank=True)
    pin_code = models.IntegerField(null=True)

    def __str__(self):
        return str(self.user)

customer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import *

from transaction.models import Transfer

class CustomerForm(ModelForm):

    class Meta:
        model = Customer
        fields=['name','birthday','phone','street','city','state','country', 'zip_code', 'pin_code']
        

class TransferForm(ModelForm):
    
    class Meta:
        model = Transfer
        fields = ['from_account', 'to_account', 'amount']
        
    def check_funds_able(self, fromValue, toValue, amount):
        print('*************************')
        print('FromValue:', fromValue)
        print('toValue:', toValue)
        print('amount:', amount)
        print('Value Check:', (fromValue - amount) < 0)
        if (fromValue - amount) < 0:
            # self._errors['amount'] = 'Insufficant Funds to Transfer.'
            raise forms.ValidationError('Insufficant Funds to Transfer.')
        return True
    
    def clean_data_get(self, field):
        data = self.cleaned_data.get(field)        
        return data

    def clean(self):
        super(TransferForm, self).clean()
        from_account = self.clean_data_get("from_account")
        to_account = self.clean_data_get("to_account")
        amount = self.clean_data_get("amount")
        self.check_funds_able(from_account.balance, to_account.balance, amount)
        
        

customer/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.conf import settings

from .forms import CustomerForm, TransferForm
from .models import Customer
from transaction.models import Transaction, Account
# Create your views here.

def index(request):
    if request.user.groups.filter(name='Employee').exists():
        return HttpResponseRedirect(reverse('employee:index'))
    return render(request, "index.html", {'bank_name': settings.BANKING_SYSTEM_NAME})

@login_required
def accounts(request):
    user = Customer.objects.get(user=request.user)
    accounts = user.account_set.select_related()
    print(accounts)
    context = {'bank_name': settings.BANKING_SYSTEM_NAME, 'accounts': accounts, 'p': user}
    return render(request, "accounts.html", context)

@login_required
def account_activity(request, account_id):
    user = Customer.objects.get(user=request.user)
    account = Account.objects.get(user=user, account_id=account_id)
    transactions = account.transaction_set.select_related().order_by('-transaction_timestamp')
    context = {
        'bank_name': settings.BANKING_SYSTEM_NAME, 
        'transactions': transactions, 
        'account': account,
        'p': user
    }
    return render(request, "account_activity.html", context)

@login_required
def transfer(request):
    user = Customer.objects.get(user=request.user)
    if request.method == 'POST':
        form = TransferForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.instance.user = user
            form.save()
            return HttpResponseRedirect(reverse('customer:accounts'))
    else:
        form = TransferForm()
    context = {
        'bank_name': settings.BANKING_SYSTEM_NAME, 
        'form': form,
    }
    return render(request, "transfer.html", context)


@login_required
def profile(request):
    if request.method == 'POST':
        customer = Customer.objects.get(user=request.user)
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('customer:accounts'))
    else:
        customer = Customer.objects.get(user=request.user)
        form = CustomerForm(instance=customer)
    context = {
        'bank_name': settings.BANKING_SYSTEM_NAME, 
        'form': form,
    }
    return render(request, "profile.html", context)

customer/templates/account_activity.html
{% extends 'base.html' %}

{% block title %}
    <title>Accounts</title>
{% endblock %}

{% block content %}
<h4>Account Details</h4>
<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Description</th>
            <th>Previous Balance</th>
            <th>Amount</th>
            <th>Currents Balance</th>
        </tr>
    </thead>
    <tbody>
        {% for transaction in transactions %}
        <tr>
            <td>{{transaction.transaction_timestamp|date:'Y-m-d H:i'}}</td>
            <td>{{transaction.type}}</td>
            <td>{{transaction.notes}}</td>
            <td>{{transaction.previous_balance}}</td>
            <td>{{transaction.amount}}</td>
            {% if transaction.current_balance < 0 %}
            <td style="color:red">{{transaction.current_balance}}</td>
            {% else %}
            <td>{{transaction.current_balance}}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
<style>
table {
    width: 100%;
    padding: 0.25rem;
    background: #ddd;
}
</style>

{% endblock %}

customer/templates/accounts.html
{% extends 'base.html' %}

{% block title %}
    <title>Accounts</title>
{% endblock %}

{% block content %}
<h4>Summary</h4>
<h6>Personal Accounts</h6>
<ul class="accounts">
{% for account in accounts %}
    {% if account.type == 'P' %}
    <li>
        <div><a href="{% url 'customer:account_activity' account_id=account.account_id %}">{{account.account_type}}</a> - ***********{{account.account_id}}</div>
        <div style="float:right">{{account.balance}}</div>
    </li>
    {% endif %}
{% endfor %}
</ul>
<h6>Loan Accounts</h6>
<ul class="accounts">
{% for account in accounts %}
    {% if account.type == 'L' %}
    <li>
        <div><a href="/accounts/{{account.account_id}}">{{account.account_type}}</a> - ***********{{account.account_id}}</div>
        <div style="float:right">{{account.balance}}</div>
    </li>
    {% endif %}
{% endfor %}
</ul>
<style>
ul.accounts {
    background: #ddd;
    padding: 1rem;
    list-style: none;
}

ul.accounts li div {
    float: left;
}

ul.accounts li {
    width: 50%;
    height: 30px;
}
</style>

{% endblock %}

customer/templates/deposit.html
{% extends 'base.html' %}

{% block title %}
    <title>Deposit</title>
{% endblock %}

{% block content %}

<h2>Welcome {{ user.username }}</h2>

    <h3>Current Balance: {{ balance }} /-</h3>
<br>
<form method="post" action="{% url "customer:amount2" %}">
{% csrf_token %}
Amount to deposit:<input type="number" name="deposit" id="deposit"/><br>
<input type="submit" value="Submit"/>
</form>

{% endblock %}

customer/templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
    <ul>
    {% if user.is_authenticated %}
        <h3>Welcome {{ user.username }}</h3>
        <h4>Services</h4>
        <li><a href="{% url "customer:edit" %}">Edit Profile</a></li>
        <li><a href="{% url "customer:withdraw" %}">Withdraw Cash</a></li>
        <li><a href="{% url "customer:deposit" %}">Deposit Cash</a></li>
        <li><a href="{% url "customer:transfer" %}">Account Transfer</a></li>
        {% else %}
        <li><a href="{% url "account_login" %}">Login</a></li>
        <li><a href="{% url "account_signup" %}">Customer Signup</a></li>
        <li><a href="{% url "account_signup" %}">Employee Signup</a></li>
    {% endif %}
    </ul>
{% endblock %}

customer/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    <title>Profile</title>
{% endblock %}

{% block content %}

<form action="{% url 'customer:profile' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

customer/templates/register.html
{% extends 'base.html' %}

{% block title %}
    <title>Register</title>
{% endblock %}

{% block content %}

    <h2>Welcome {{ user.username }}</h2>
<h2>Registeration</h2>
    <form method="post" action="{{ form_url }}" >
{% csrf_token %}
        <table>
            {{ customerform }}
        </table>

<tr><td><input type="submit" value="{% if not type == "edit" %}Submit{% else %}Update{% endif %}" name="submit"/></td></tr>
</form>

{% endblock %}

customer/templates/transfer.html
{% extends 'base.html' %}

{% block title %}
    <title>Account Transfer</title>
{% endblock %}

{% block content %}

<form action="{% url 'customer:transfer' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<style>
ul.errorlist.nonfield {
    list-style: none;
    background: #e43e3e94;
    color: white;
    font-size: larger;
    font-weight: bold;
    padding: 1rem;
    border-radius: 10px;
}
</style>

{% endblock %}

customer/templates/withdraw.html
{% extends 'base.html' %}

{% block title %}
    <title>Withdrawal</title>
{% endblock %}

{% block content %}

<h2>Welcome {{ user.username }}</h2>
    {% for user in set %}
    <h3>Current Balance: {{ user.balance }} /-</h3><br>
{% endfor %}
<form method="post" action="{% url "customer:amount" %}">
{% csrf_token %}
Amount to withdraw:<input type="number" name="withdraw" id="withdraw"/><br>
<input type="submit" value="Submit"/>
</form>

{% endblock %}